apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: testnodejs0319a-gitops
  description: This is GitOps manifest for testnodejs0319a   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: testnodejs0319a
    janus-idp.io/tekton: testnodejs0319a 
    backstage.io/kubernetes-id: testnodejs0319a 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:testnodejs0319a
