apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: testnodejs0319a
  janus-idp.io/tekton: testnodejs0319a
  backstage.io/kubernetes-id: testnodejs0319a
  backstage.io/kubernetes-namespace: testnodejs0319a 
  app.kubernetes.io/part-of: testnodejs0319a
resources: 
- deployment.yaml
- route.yaml
- service.yaml
