apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: testnodejs0319a
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testnodejs0319a 
  name: testnodejs0319a
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: testnodejs0319a
    weight: 100 
